query GetAllPokemon($limit: Int!) {
  pokemon_v2_pokemon(limit: $limit) {
    id
    name
    height
  }
}

query PokemonByType($type: String!, $limit: Int!) {
  pokemon_v2_pokemon(
    where: {
      pokemon_v2_pokemontypes: { pokemon_v2_type: { name: { _eq: $type } } }
    }
    limit: $limit
  ) {
    id
    name
    height
    }
  }
}
